openapi: 3.0.0
info:
  title: API TRUFO
  description: API para el registro y consulta de avistamientos de OVNIs.
  version: "1.0.0"
security:
  - ApiKeyAuth: []
  

paths:
  /sightings:
    get:
      security:
        - ApiKeyAuth: []
      summary: Obtiene una lista de avistamientos
      description: Devuelve una lista de registros de avistamientos. Se pueden aplicar filtros por ciudad, estado, país, forma y rango de fechas, 
        además de usar paginación.
      parameters:
        - name: page
          in: query
          description: Número de página para la paginación (por defecto 1)
          required: false
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          description: Número de resultados por página (por defecto 10)
          required: false
          schema:
            type: integer
            default: 10
        - name: city
          in: query
          description: Filtrar por ciudad
          required: false
          schema:
            type: string
        - name: state
          in: query
          description: Filtrar por estado
          required: false
          schema:
            type: string
        - name: country
          in: query
          description: Filtrar por país
          required: false
          schema:
            type: string
        - name: shape
          in: query
          description: Filtrar por forma del OVNI
          required: false
          schema:
            type: string
        - name: from_datetime
          in: query
          required: false
          schema:
            type: string
            format: date-time
        - name: to_datetime
          in: query
          required: false
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: Lista de avistamientos correspondiente a los filtros aplocados.
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                    description: Número total de avistamientos que cumplen con los filtros
                  page:
                    type: integer
                    description: Página actual
                  limit:
                    type: integer
                    description: Cantidad de resultados por página
                  sightings:
                    type: array
                    items:
                      $ref: '#/components/schemas/Sighting'
        '500':
          description: Error interno del servidor

    post:
      security:
        - ApiKeyAuth: []
      summary: Crea un nuevo avistamiento
      description: Añade un nuevo OVNI a la DB
      requestBody:
        description: Objeto con la información del avistamiento a crear
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Sighting'
      responses:
        '201':
          description: Avistamiento creado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Sighting'
        '400':
          description: Datos incorrectos

  /sightings/{sightingId}:
    get:
      security:
        - ApiKeyAuth: []
      summary: Obtiene un avistamiento específico
      description: Devuelve la información de un avistamiento por id
      parameters:
        - name: sightingId
          in: path
          description: Id del avistamiento
          required: true
          schema:
            type: string
        - name: page
          in: query
          description: Número de página para la paginación (por defecto 1)
          required: false
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          description: Número de resultados por página (por defecto 10)
          required: false
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: Avistamiento obtenido correctamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Sighting'
        '404':
          description: Avistamiento no encontrado

    put:
      security:
        - ApiKeyAuth: []
      summary: Actualiza un avistamiento existente
      description: Modifica los datos de un avistamiento especifico
      parameters:
        - name: sightingId
          in: path
          description: Id del avistamiento
          required: true
          schema:
            type: string
      requestBody:
        description: Objeto con los datos actualizados del avistamiento.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Sighting'
      responses:
        '200':
          description: Avistamiento actualizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Sighting'
        '400':
          description: Datos incorrectos, no actualizado
        '404':
          description: Avistamiento no encontrado

    delete:
      security:
        - ApiKeyAuth: []
      summary: Elimina un avistamiento
      description: Elimina el registro de un avistamiento identificado por su ID.
      parameters:
        - name: sightingId
          in: path
          description: Id del avistamiento
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Avistamiento eliminado exitosamente
        '404':
          description: Avistamiento no encontrado
  /sightings/country:
    get:
      security:
        - ApiKeyAuth: []
      summary: Obtiene una lista de avistamientos por país
      description: Devuelve una lista de avistamientos filtrados por país.
      parameters:
        - name: country
          in: query
          description: Nombre del país para filtrar los avistamientos
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Lista de avistamientos obtenida correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Sighting'
        '500':
          description: Error interno del servidor
    
  /locations:
    get:
      security:
        - ApiKeyAuth: []
      summary: Obtiene una lista de ubicaciones
      description: Devuelve una lista de ubicaciones donde han ocurrido avistamientos.
      responses:
        '200':
          description: Lista de ubicaciones obtenida correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/location'
        '500':
          description: Error interno del servidor
  
  /people:
    get:
      security:
        - ApiKeyAuth: []
      summary: Obtiene una lista de personas
      description: Devuelve una lista de personas que han reportado avistamientos.
      responses:
        '200':
          description: Lista de personas obtenida correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/People'
        '500':
          description: Error interno del servidor
    post:
      security:
        - ApiKeyAuth: []
      summary: Crea una nueva persona
      description: Añade una nueva persona a la base de datos.
      requestBody:
        description: Objeto con la información de la persona a crear
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/People'
      responses:
        '201':
          description: Persona creada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/People'
        '400':
          description: Datos incorrectos
      
    

components:
  schemas:
    Sighting:
      type: object
      description: Registro de un avistamiento de OVNIs.
      properties:
        id:
          type: string
          description: Identificador único del avistamiento.
          example: "1"
        datetime:
          type: string
          format: date-time
          description: Fecha y hora del avistamiento.
          example: "1949-10-10T20:30:00Z" 
        shape:
          type: string
          description: Forma del objeto avistado.
          example: "cylinder"
        duration_seconds:
          type: integer
          description: Duración del avistamiento en segundos.
          example: 2700
        duration_human:
          type: string
          description: Duración del avistamiento en formato legible (por ejemplo, "45 minutes").
          example: "45 minutes"
        comments:
          type: string
          description: Comentarios o detalles adicionales sobre el avistamiento.
          example: "This event took place in early fall after a Boy Scout meeting..."
        date_posted:
          type: string
          format: date
          description: Fecha en que se publicó el reporte.
          example: "2004-04-27"
        latitude:
          type: number
          format: float
          description: Latitud del lugar donde ocurrió el avistamiento.
          example: 29.8830556
        longitude:
          type: number
          format: float
          description: Longitud del lugar donde ocurrió el avistamiento.
          example: -97.9411111
        index_people:
          type: integer
          description: Numero indentificador de la persona que ha registrado el avistamiento en la base de datos (Quién lo ha visto).
          example: 223
      required:
        - datetime
        - city
        - country
        - shape
        - date_posted
        - latitude
        - longitude
        - index_people
    location:
      type: object
      description: Ubicación del avistamiento.
      properties:
        city:
          type: string
          description: Ciudad donde ocurrió el avistamiento.
          example: "San Antonio"
        state:
          type: string
          description: Estado donde ocurrió el avistamiento.
          example: "Texas"
        country:
          type: string
          description: País donde ocurrió el avistamiento.
          example: "United States"
        latitude:
          type: number
          format: float
          description: Latitud del lugar donde ocurrió el avistamiento.
          example: 29.8830556
        longitude:
          type: number
          format: float
          description: Longitud del lugar donde ocurrió el avistamiento.
          example: -97.9411111
      required:
        - city
        - state
        - country
    People:
      type: object
      description: Persona que ha registrado un avistamiento
      properties:
        index_people:
          type: integer
          description: Número identificador de la persona que ha registrado el avistamiento en la base de datos (Quién lo ha visto).
          example: 223
        firstName:
          type: string
          description: Nombre de la persona que ha registrado el avistamiento.
          example: "John"
        lastName:
          type: string
          description: Apellido de la persona que ha registrado el avistamiento.
          example: "Doe"
        company:
          type: string
          description: Empresa donde trabaja la persona que ha registrado el avistamiento.
          example: "Tech Corp"
        Phone:
          type: string
          description: Número de teléfono de la persona que ha registrado el avistamiento.
          example: "+1-234-567-8900"
        email:
          type: string
          description: Correo electrónico de la persona que ha registrado el avistamiento.
          example: "urangel@espinoza-francis.net"
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
      description: Clave de API para autenticar las solicitudes.